### ISSUE TITLE
HTTP proxies

### ISSUE THREAD

**Issue by Axel-uwu** [iojw/socialscan#12]
When I try to run it, it says an error, that only http proxies work, I'm pretty sure my proxies are indeed HTTP but it still prints the same error even after trying other proxies.

**Comment by iojw** [comment]
@Axel-uwu Did you include the "http://" in front of each URL inside the text file? That is required.

**Comment by Axelu2020** [comment]
> @Axel-uwu Did you include `http://` in front of each URL inside the text file? That is currently required.

Adding http:// works, you can close the issue as im the owner of the acocunt that made the issue request, sorry about it I just noticed
