### ISSUE TITLE
per service: ClientConnectorCertificateError SSL: CERTIFICATE_VERIFY_FAILED certificate verify failed

### ISSUE THREAD

**Issue by buckleyc** [iojw/socialscan#14]
Not sure what is causing this, but each service check is resulting in a similar certificate error message.
Attempted from both shell command line (e.g."socialscan username") and from within python3 interpreter.
OS: Mac OS X 10.15.2
Python: 3.8.1
Messages:
> GitHub: ClientConnectorCertificateError - Cannot connect to host github.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
GitLab: ClientConnectorCertificateError - Cannot connect to host gitlab.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Instagram: ClientConnectorCertificateError - Cannot connect to host instagram.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Lastfm: ClientConnectorCertificateError - Cannot connect to host www.last.fm:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Pastebin: ClientConnectorCertificateError - Cannot connect to host pastebin.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Reddit: ClientConnectorCertificateError - Cannot connect to host www.reddit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Snapchat: ClientConnectorCertificateError - Cannot connect to host accounts.snapchat.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Tumblr: ClientConnectorCertificateError - Cannot connect to host tumblr.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Twitter: ClientConnectorCertificateError - Cannot connect to host api.twitter.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
Yahoo: ClientConnectorCertificateError - Cannot connect to host login.yahoo.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]

**Comment by iojw** [comment]
@buckleyc Hi, for OSX I believe you have to execute the `Install Certificates.command` file that came with your Python installation. The error isn’t due to socialscan, but rather a requirement of Python on OSX. See https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

**Comment by buckleyc** [comment]
And that was it! Thank you, iojw.
From commandline (for anyone with same issue):
> open "/Applications/Python 3.8/Install Certificates.command"
