### ISSUE TITLE
Instagram: QueryError

### ISSUE THREAD

**Issue by fastfire** [iojw/socialscan#19]
When I run socialscan, always get this:
Instagram: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.

**Comment by iojw** [comment]
@fastfire Are you from the EU? This might be a duplicate of #17. I am working on it but in the meantime you can use a VPN to get around it.

**Comment by fastfire** [comment]
@iojw Yes, I'm from EU. Thank you!
