### ISSUE TITLE
not accurate results 

### ISSUE THREAD

**Issue by pretech86** [iojw/socialscan#21]
thanks for the tool but i test it on my personal ,mails and it give non accurate results

**Comment by iojw** [comment]
@pretech86 Hi, these inaccurate results are for which platforms?

**Comment by pretech86** [comment]
All

**Comment by iojw** [comment]
@pretech86 All tests are currently passing for me. Are your queries in a valid email format? Otherwise the tool will treat it as a username. Could you also share the output of the tool when running `socialscan YOUR_EMAIL -v`?

**Comment by pretech86** [comment]
socialscan 1.2.0

**Comment by pretech86** [comment]
socialscan MY_EMAIL --platforms github 
it give me ... github >> green color that means avaliable but i don't have any github account with this mail

**Comment by iojw** [comment]
@pretech86 Available refers to the fact that the account is available for registration and the email is not in use, meaning the tool is working as intended.

**Comment by pretech86** [comment]
thanks it working
