### ISSUE TITLE
Only getting SSL CERTIFICATE VERIFY FAILED errors.

### ISSUE THREAD

**Issue by DevJoris** [iojw/socialscan#26]
Just installed socialscan and im only getting certificate errors. I saw connecting to a VPN might help. Sadly it didn't. Any help?
Using ProtonVPN and python 3.7
<img width="1558" alt="Screenshot 2020-10-11 at 12 21 15" src="https://user-images.githubusercontent.com/29674149/95676122-438cf300-0bbc-11eb-8bfd-b9cabab34809.png">

**Comment by iojw** [comment]
There was a similar issue in #14, try the fix there.

**Comment by DevJoris** [comment]
> There was a similar issue in #14, try the fix there.

Yep that fixed it. Thank you!

**Comment by Elior1010** [comment]
its for mac OS i tried looking all over and it still a fail for me

**Comment by iojw** [comment]
@Elior1010 Have you tried the steps listed above?

**Comment by iojw** [comment]
Closing for now since there's no update. Let me know if you still face the issue.
