### ISSUE TITLE
'socialscan' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by ahmedali0352** [iojw/socialscan#28]
after installing using the command line > pip install socialscan  , the command socialscan shows "'socialscan' is not recognized as an internal or external command, operable program or batch file" but when i try to rerun the installation of the package it says requirement already satisfied

**Comment by iojw** [comment]
It sounds like your PATH isn't configured correctly. Try searching online for how to include pip's installlation directory into the PATH for your system.

**Comment by iojw** [comment]
Closing for now since there's no update. Feel free to comment if you still face the issue.
