### ISSUE TITLE
getaddrinfo failed

### ISSUE THREAD

**Issue by crimvirt** [iojw/socialscan#29]
It was working earlier but now there is an error:
[USERNAME]: ClientConnectorError - Cannot connect to host tumblr.com:443 ssl:default [getaddrinfo failed]

**Comment by iojw** [comment]
Does this only occur for one username or all usernames? Try running `socialscan USERNAME -p tumblr --debug` and include the output.

**Comment by iojw** [comment]
Closing this since you opened another issue at #32
