### ISSUE TITLE
Connection timeout to host https://tumblr.com/register

### ISSUE THREAD

**Issue by crimvirt** [iojw/socialscan#32]
I don't know why this happens but the site "https://tumblr.com/register" is still accessible to my browser. I tried to wait for a couple of days/weeks and this still happens. 

There are two different errors:

[USERNAME]: Connection timeout to host https://tumblr.com/register

[USERNAME]: Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.

____________________________________________________________________________________________________
I tried to use well-working proxies by trying to run it on browser one by one, and then I tried to use it to SocialScan but this is the output logs:

----------------------------------------
                 Tumblr
----------------------------------------
30goalsedu: ServerTimeoutError - Connection timeout to host https://tumblr.com/register
7docilechainshattersthevoid: ServerDisconnectedError -
99media: ClientProxyConnectionError - Cannot connect to host 193.193.224.170:3128 ssl:default [Connect call failed ('193.193.224.170', 3128)]
acentricmag: ClientHttpProxyError - 400, message='Bad Request', url=URL('http://35.234.46.196:8080')
adrturz: ServerTimeoutError - Connection timeout to host https://tumblr.com/register
ainaleonievera: ClientProxyConnectionError - Cannot connect to host 95.47.255.181:3128 ssl:default [Connect call failed ('95.47.255.181', 3128)]
aldochaconphotographer: ClientHttpProxyError - 400, message='Bad Request', url=URL('http://47.91.153.45:80')
alexzimmerportfolio: ServerTimeoutError - Connection timeout to host https://tumblr.com/register
aliceindrugsworld: ClientHttpProxyError - 400, message='Bad Request', url=URL('http://118.179.223.130:80')
alisemorales: ServerDisconnectedError -
alpestris-flowers: ClientHttpProxyError - 400, message='Bad Request', url=URL('http://85.84.14.9:80')
alphachiomegaunlblog: ServerDisconnectedError -
alwaysreadhello: ClientHttpProxyError - 400, message='Bad Request', url=URL('http://47.243.22.216:80')
alyssaking9583: ServerTimeoutError - Connection timeout to host https://tumblr.com/register
angelic-kouhai: ClientOSError - [WinError 10054] An existing connection was forcibly closed by the remote host
anteaterlovestories: ServerDisconnectedError -

Available, Taken/Reserved, Invalid, Error
Completed 16 queries in 15.26s

**Comment by iojw** [comment]
Does this only occur with the proxies you are using or does it occur even without a proxy?

**Comment by crimvirt** [comment]
It does occur both without proxies and with proxies

**Comment by crimvirt** [comment]
This is the output when there's no proxy:

----------------------------------------
                 Tumblr
----------------------------------------
30goalsedu: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
7docilechainshattersthevoid: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
99media: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
acentricmag: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
adrturz: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
ainaleonievera: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
aldochaconphotographer: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
alexzimmerportfolio: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
aliceindrugsworld: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
alisemorales: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
alpestris-flowers: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
alphachiomegaunlblog: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
alwaysreadhello: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
alyssaking9583: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
angelic-kouhai: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
anteaterlovestories: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.

Available, Taken/Reserved, Invalid, Error
Completed 16 queries in 19.94s

**Comment by iojw** [comment]
Ok, I'm able to reproduce the issue with Tumblr locally. I'll take a look when I get the time if no one else gets to it first.

**Comment by crimvirt** [comment]
> Ok, I'm able to reproduce the issue with Tumblr locally. I'll take a look when I get the time

Hello there, any news?

**Comment by iojw** [comment]
I've pushed a fix for this in v1.4.2

**Comment by crimvirt** [comment]
> I've pushed a fix for this in v1.4.2 - it should no longer occur

I tried 1.4.2 and it still occurs the same exact problem

**Comment by iojw** [comment]
Can you run a command with the `--debug` flag and send the output here?

**Comment by crimvirt** [comment]
> Does it work with only 1 query?

No, it occurs to every queries.

**Comment by crimvirt** [comment]
> Does it work with only 1 query?

I even tried using vpn to see if it works, but it doesn't.
