### ISSUE TITLE
only http proxies are supported

### ISSUE THREAD

**Issue by Axelu2020** [iojw/socialscan#33]
Hey again, I'm sorry for making another issue when I've already made one previously, but I can't reopen it so here I am, I've tried to use socialscan as a library and it worked for a while, but I had to reinstall everything after a system format, anyways.
I'm trying to use proxies but it always errors out with "**only http proxies are  supported"**, I did try adding _http://_ before each line, even tried different proxies and different formats and made sure my proxies are http, but still. it always returns that error

**Comment by iojw** [comment]
Can you post an example of the format of the proxies you are using? socialscan uses [aiohttp](https://github.com/aio-libs/aiohttp/) to make its requests, and from what I've seen as long as the URL scheme is `http`, your error shouldn't be raised. Are you using HTTPS proxies by any chance?

**Comment by iojw** [comment]
Closing for now since there's no update. Feel free to comment if you still face the issue.
