### ISSUE TITLE
No module named 'socialscan.util'; 'socialscan' is not a package

### ISSUE THREAD

**Issue by UmerYasin1** [iojw/socialscan#37]
I had install SocialScan using this command " pip install socialscan " but still I am getting this error ...

Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\project\email-saga-master\socialscan.py", line 1, in <module>
    from socialscan.util import Platforms, sync_execute_queries
  File "C:\Users\lenovo\Desktop\project\email-saga-master\socialscan.py", line 1, in <module>
    from socialscan.util import Platforms, sync_execute_queries
ModuleNotFoundError: No module named 'socialscan.util'; 'socialscan' is not a package

**Comment by iojw** [comment]
What is the command you are running that causes the above error?

**Comment by UmerYasin1** [comment]
When I run my program this error pop up in terminal ....

**Comment by UmerYasin1** [comment]
My code :

from socialscan.util import Platforms, sync_execute_queries
import pandas

INPUT_FILE = 'Book1.xlsx'

df = pandas.read_excel(INPUT_FILE, 'Sheet1', usecols=['Emails'])
listt =df['Emails'].tolist()


platforms = [Platforms.GITHUB, Platforms.LASTFM , Platforms.Instagram,
             Platforms.Twitter, Platforms.Tumblr, Platforms.Pinterest,
             Platforms.Spotify, Platforms.Firefox, Platforms.Pinterest]

results = sync_execute_queries(listt, platforms)
for result in results:
    print(f"{result.query} on {result.platform}: {result.message} (Success: {result.success}, Valid: {result.valid}, Available: {result.available})")

**Comment by iojw** [comment]
It may be because your file is named `socialscan.py`. Try a different name.

**Comment by UmerYasin1** [comment]
Thanks It works ..... I need one more help when i run my code i got this error in terminal .....

 raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

Can you please resolve it .....

**Comment by iojw** [comment]
What's your OS and Python version?

**Comment by UmerYasin1** [comment]
I am Using Python 3.9 and Window 10 OS 
And Code editor Pycharm ....

**Comment by iojw** [comment]
This is related to #2. 

Closing this as it is stale. If this issue still occurs, could you post more details about the socialscan version you are using in that issue?
