### ISSUE TITLE
Proxy issues 

### ISSUE THREAD

**Issue by BusraSunar** [iojw/socialscan#54]
Hi, sorry I already asked on one of the closed issues but i wanted to ask as a new issue. I am having proxy issues in my code, I am using free proxy servers that I have gathered but even though I have tried what you have suggested (and they are http) I am getting server timeout error.
When I make my array like this,
```

proxyList = [
"http://178.128.178.169:3128",
"http://167.99.163.146:3128",
"http://167.172.203.244:8118"
]
```

I get server timeout error. If I make my array like this,
```

proxyList = [
"178.128.178.169:3128",
"167.99.163.146:3128",
"167.172.203.244:8118"
]
```

I get invalid url error.
What am i doing wrong here, can you please help me?

**Comment by iojw** [comment]
The format in the first code block is correct. You are likely getting a timeout error because of issues with the free proxy server - are you able to verify that they work correctly?

Closing as it is a stale issue. Let me know if you still face the issue.
