### ISSUE TITLE
Client connector certificate error 

### ISSUE THREAD

**Issue by adfrank99** [iojw/socialscan#57]
Keep getting this error and wondering how to rectify this? Thanks

Firefox: ClientConnectorCertificateError - Cannot connect to host api.accounts.firefox.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '52.89.11.225'. (_ssl.c:1045)")]
GitHub: ClientConnectorCertificateError - Cannot connect to host github.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '13.237.44.5'. (_ssl.c:1045)")]
Instagram: ClientConnectorCertificateError - Cannot connect to host instagram.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '157.240.8.174'. (_ssl.c:1045)")]
Lastfm: ClientConnectorCertificateError - Cannot connect to host www.last.fm:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '151.101.29.188'. (_ssl.c:1045)")]
Pinterest: ClientConnectorCertificateError - Cannot connect to host www.pinterest.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '2.18.52.37'. (_ssl.c:1045)")]
Spotify: ClientConnectorCertificateError - Cannot connect to host spclient.wg.spotify.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '35.186.224.25'. (_ssl.c:1045)")]
Tumblr: ClientConnectorCertificateError - Cannot connect to host tumblr.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '192.0.77.40'. (_ssl.c:1045)")]
Twitter: ClientConnectorCertificateError - Cannot connect to host api.twitter.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '104.244.42.130'. (_ssl.c:1045)")]

**Comment by iojw** [comment]
It's an issue with your ISP or the proxy you are using as the SSL certificate cannot be verified.

Closing as it is a stale issue. Let me know if you still face the issue.
