### ISSUE TITLE
Instagram Endpoint

### ISSUE THREAD

**Issue by runescapes** [iojw/socialscan#58]
Was wondering if there was a fix for this. It seems https://www.instagram.com/accounts/web_create_ajax/attempt/ is returning a 405 error for me on mobile and pc. Not sure if it's just my end or they've changed the endpoint that can be used?

**Comment by skybluedoves** [comment]
Not working for me either.

**Comment by iojw** [comment]
Hey there, I'm currently busy so I don't the time to look into this, but I'll do so when I get the time. In the meantime, you're free to poke around the source code and I can answer any questions you have.

**Comment by runescapes** [comment]
> Hey there, I'm currently busy so I don't the time to look into this, but I'll do so when I get the time. In the meantime, you're free to poke around the source code and I can answer any questions you have.

okay, no problem! i was looking at the source code and couldn't seem to get it to work, but that's fine, no biggie. I could happily pay for your time as well, if you'd like to message me somewhere!

**Comment by iojw** [comment]
Thanks for your patience! This is fixed in the latest release.
