### ISSUE TITLE
updated to v2.0.0; query errors

### ISSUE THREAD

**Issue by tsmitsmitonline** [iojw/socialscan#59]
Getting:

Instagram: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
Lastfm: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.

**Comment by iojw** [comment]
Does it work if you wait for a while before trying again?

**Comment by tsmitsmitonline** [comment]
I tested several times, with same error result...

Tumblr
Firefox
GitHub
Pinterest
Twitter
Instagram: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.
Lastfm: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.

Available, Taken/Reserved, Invalid, Error
Completed 11 queries in 1.85s

**Comment by iojw** [comment]
This could be because a different version of Instagram is being served. Try running `socialscan USERNAME -p instagram --debug` and provide the output?

**Comment by tsmitsmitonline** [comment]
I get this:

socialscan afcajax -p instagram --debug
DEBUG:root:GET https://www.instagram.com/api/v1/public/landing_info/
----------------------------------------
                 afcajax
----------------------------------------
Instagram: QueryError - Could not retrieve token. You might be sending too many requests. Use a proxy or wait before trying again.

**Comment by iojw** [comment]
This should be fixed in 2.0.1. Thank you for your patience!
