### ISSUE TITLE
Installation problem!

### ISSUE THREAD

**Issue by ItsBeno** [iojw/socialscan#7]
I can't install please help...
![Screenshot-at-2019-08-12-16-19-15 1](https://user-images.githubusercontent.com/27826498/62895698-b51aa880-bd4f-11e9-9d42-93799e720d37.png)

`https://postimg.cc/qNMgDwyf`

**Comment by iojw** [comment]
@ItsBeno I think you might be using a Python 2 installation. The minimum version for this utility is Python 3.7 so you'll need to update Python on your system.

**Comment by 51lentb0b** [comment]
That helped me, thanks a lot! 

pip3 install socialscan .

**Comment by ishandutta2007** [comment]
> @ItsBeno I think you might be using a Python 2 installation. The minimum version for this utility is Python 3.7 so you'll need to update Python on your system.

thanks that was indeed the issue, but please call out versions supported clearly in documentations.

**Comment by iojw** [comment]
@ishandutta2007  Where were you looking for this? The minimum version for this tool is stated on both the README and PyPI page.

**Comment by ishandutta2007** [comment]
@iojw [here](https://github.com/iojw/socialscan/blob/master/README.md)
line number ?

**Comment by iojw** [comment]
@ishandutta2007 The badge on the line 5.

**Comment by ishandutta2007** [comment]
> @ishandutta2007 The badge on the line 5.

I see. My bad not used to reading badges.

**Comment by ishandutta2007** [comment]
By the way the badge says 3.6+,  it didn't work in 3.6.0, it worked in 3.7.0

**Comment by iojw** [comment]
@ishandutta2007 I can see how one might gloss over the badge since it's quite small. I'll try to make the version requirements more visible then. Thank you for bringing this up!

**Comment by iojw** [comment]
The update for compatibility with 3.6 was just pushed a few days ago and hasn't been deployed yet. If you need it you can clone the latest version of master.
