### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by yousef1y2** [iojw/socialscan#8]
How can I use the proxy?

**Comment by iojw** [comment]
@yousef1y2 You can list all HTTP proxies in a text file (one on each line) and run socialscan with the following flag  `--proxy-list YOUR_PROXY_LIST.txt`

**Comment by BusraSunar** [comment]
Hi, I am having proxy issues in my code, I am using free proxy servers that I have gathered but even though I have tried what you have suggested (and they are http) I am getting server timeout error. 
When I make my array like this, 
proxyList = [
    "http://178.128.178.169:3128",
    "http://167.99.163.146:3128",
    "http://167.172.203.244:8118"
]
I get server timeout error. If I make my array like this,  
proxyList = [
    "178.128.178.169:3128",
    "167.99.163.146:3128",
    "167.172.203.244:8118"
]

I get invalid url error. 
What am i doing wrong here,  can you please help me?
